name: push_by_token_tester
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth: ^1.6.0
  provider: ^6.1.2
  http: ^1.2.1
  auto_size_text: ^3.0.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true